import { expect, test, type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import path from 'node:path';

async function open(page: Page, outcome: string) {
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
  for (const [pattern, name] of [
    ['**/.vite/deps/aws-amplify_auth.js*', 'symptom-auth.mock.js'],
    ['**/src/lib/api.ts*', 'imaging-api.mock.js'],
  ]) await page.route(pattern, route => route.fulfill({ contentType: 'application/javascript',
    body: readFileSync(path.join(process.cwd(), 'e2e/fixtures', name), 'utf8') }));
  await page.addInitScript(value => { (window as unknown as { __imageOutcome: string }).__imageOutcome = value; }, outcome);
  await page.goto('/e2e/fixtures/imaging-safety.html');
  await expect(page.getByText('Synthetic Patient', { exact: true }).first()).toBeVisible();
  await page.getByRole('tab', { name: /Hybrid AI Analysis/ }).click();
  await page.locator('input[accept="image/*"]').setInputFiles({ name: 'test.png', mimeType: 'image/png', buffer: Buffer.from('synthetic image') });
}

for (const outcome of ['unavailable', 'malformed']) test(`actual image upload does not fabricate findings for ${outcome}`, async ({ page }) => {
  await open(page, outcome);
  await expect(page.getByRole('alert')).toContainText('Image analysis unavailable');
  await expect(page.getByRole('button', { name: 'Select File to Analyze' })).toBeEnabled();
  await expect(page.getByText(/Clear lung fields|DEMO MODE|Analysis Complete|Generated by Claude/)).toHaveCount(0);
});

test('actual upload labels successful output as an unreviewed draft', async ({ page }) => {
  await open(page, 'available');
  await expect(page.getByText('Synthetic analysis for clinician review')).toBeVisible();
  await expect(page.getByText('Unreviewed AI draft')).toBeVisible();
  await expect(page.getByText(/Generated by Claude|Google Vision/)).toHaveCount(0);
});

test('leaving the actual upload page prevents a late result from appearing', async ({ page }) => {
  await open(page, 'hold');
  await expect.poll(() => page.evaluate(() => typeof (window as unknown as { __finishImage?: () => void }).__finishImage)).toBe('function');
  await page.getByRole('button', { name: 'Leave test imaging' }).click();
  await page.evaluate(() => (window as unknown as { __finishImage: () => void }).__finishImage());
  await expect(page.getByText('Synthetic late analysis')).toHaveCount(0);
});
