import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import type { ReactNode } from 'react';
import HealthRecords from '@/pages/HealthRecords';

const mocks = vi.hoisted(() => ({ post: vi.fn(), get: vi.fn(), toast: vi.fn(),
  listeners: new Set<(event: { payload: { event: string } }) => void>() }));
vi.mock('react-router-dom', () => ({ useNavigate: () => vi.fn() }));
vi.mock('aws-amplify/auth', () => ({ getCurrentUser: async () => ({ userId: 'test-patient' }) }));
vi.mock('aws-amplify/utils', () => ({ Hub: { listen: (_channel: string, callback: (event: { payload: { event: string } }) => void) => {
  mocks.listeners.add(callback); return () => mocks.listeners.delete(callback);
} } }));
vi.mock('@/lib/api', () => ({ api: { post: mocks.post, get: mocks.get } }));
vi.mock('@/lib/secure-storage', () => ({ getUser: () => ({ id: 'test-patient', name: 'Synthetic Patient' }),
  setUser: vi.fn(), clearAllSensitive: vi.fn(), SESSION_CLEARED_EVENT: 'test-session-cleared' }));
vi.mock('@/hooks/use-toast', () => ({ useToast: () => ({ toast: mocks.toast }) }));
vi.mock('@/components/layout/DashboardLayout', () => ({ DashboardLayout: ({ children }: { children: ReactNode }) => <main>{children}</main> }));
beforeEach(() => {
  vi.clearAllMocks();
  mocks.listeners.clear();
  mocks.get.mockImplementation(async (url: string) => url.startsWith('/relationships') ? { connections: [] } : { name: 'Synthetic Patient' });
  vi.stubGlobal('FileReader', class {
    onload: ((event: { target: { result: string } }) => void) | null = null;
    abort() {}
    readAsDataURL() { this.onload?.({ target: { result: 'data:image/png;base64,dGVzdA==' } }); }
  });
});
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });

function openImaging() {
  const view = render(<HealthRecords />);
  fireEvent.mouseDown(screen.getByRole('tab', { name: /AI/i }), { button: 0, ctrlKey: false });
  const input = view.container.querySelector('input[accept="image/*"]')!;
  const select = () => fireEvent.change(input, { target: { files: [new File(['synthetic image'], 'test.png', { type: 'image/png' })] } });
  return { ...view, select };
}

it('labels actual analysis as an unreviewed draft without invented provider attribution', async () => {
  mocks.post.mockImplementation(async url => url === '/ehr' ? [] : { analysis: 'Synthetic findings for review', provider: 'test-provider' });
  const view = openImaging(); view.select();
  await screen.findByText('Synthetic findings for review');
  expect(screen.getByText('Unreviewed AI draft')).toBeInTheDocument();
  expect(screen.queryByText(/Generated by Claude|Analysis Complete|Google Vision/)).not.toBeInTheDocument();
});

it.each(['', '  ', { diagnosis: 'Synthetic nested object' }])('rejects malformed analysis %j', async analysis => {
  mocks.post.mockImplementation(async url => url === '/ehr' ? [] : { analysis });
  const view = openImaging(); view.select();
  await screen.findByRole('alert');
  expect(screen.queryByText('Unreviewed AI draft')).not.toBeInTheDocument();
});

it.each(['unmount', 'session-clear'])('ignores a late analysis after %s', async event => {
  let finish!: (data: unknown) => void;
  mocks.post.mockImplementation(url => url === '/ehr' ? Promise.resolve([]) : new Promise(resolve => { finish = resolve; }));
  const view = openImaging(); view.select();
  await waitFor(() => expect(finish).toBeDefined());
  if (event === 'unmount') view.unmount();
  else act(() => window.dispatchEvent(new Event('test-session-cleared')));
  await act(async () => finish({ analysis: 'Synthetic late result' }));
  expect(screen.queryByText('Synthetic late result')).not.toBeInTheDocument();
  expect(mocks.toast).not.toHaveBeenCalled();
});

it('keeps a newer image result when the older request completes last', async () => {
  const pending: Array<(data: unknown) => void> = [];
  mocks.post.mockImplementation(url => url === '/ehr' ? Promise.resolve([]) : new Promise(resolve => pending.push(resolve)));
  const view = openImaging(); view.select(); view.select();
  await act(async () => pending[1]({ analysis: 'Synthetic newest result' }));
  await act(async () => pending[0]({ analysis: 'Synthetic old result' }));
  expect(screen.getByText('Synthetic newest result')).toBeInTheDocument();
  expect(screen.queryByText('Synthetic old result')).not.toBeInTheDocument();
});

it('reports a file read error without dispatching image analysis', async () => {
  vi.stubGlobal('FileReader', class {
    onerror: (() => void) | null = null;
    abort() {}
    readAsDataURL() { this.onerror?.(); }
  });
  mocks.post.mockResolvedValue([]);
  const view = openImaging(); view.select();
  await screen.findByRole('alert');
  expect(mocks.post.mock.calls.filter(([url]) => url === '/ai/imaging')).toHaveLength(0);
  expect(screen.getByRole('button', { name: /Select File/i })).toBeEnabled();
});

it('ignores a stale file-reader callback after a newer selection', async () => {
  const readers: Array<{ onload: ((event: { target: { result: string } }) => void) | null }> = [];
  vi.stubGlobal('FileReader', class {
    onload: ((event: { target: { result: string } }) => void) | null = null;
    abort() {}
    readAsDataURL() { readers.push(this); }
  });
  mocks.post.mockImplementation(async url => url === '/ehr' ? [] : { analysis: 'Synthetic newest image' });
  const view = openImaging(); view.select(); view.select();
  await act(async () => readers[1].onload?.({ target: { result: 'data:image/png;base64,bmV3' } }));
  await act(async () => readers[0].onload?.({ target: { result: 'data:image/png;base64,b2xk' } }));
  const requests = mocks.post.mock.calls.filter(([url]) => url === '/ai/imaging');
  expect(requests).toHaveLength(1);
  expect(requests[0][1].imageBase64).toBe('bmV3');
});

it.each(['signedIn', 'signedOut', 'tokenRefresh_failure'])('rejects a late imaging response after Hub %s', async event => {
  let finish!: (data: unknown) => void;
  mocks.post.mockImplementation(url => url === '/ehr' ? Promise.resolve([]) : new Promise(resolve => { finish = resolve; }));
  const view = openImaging(); view.select();
  await waitFor(() => expect(finish).toBeDefined());
  act(() => mocks.listeners.forEach(callback => callback({ payload: { event } })));
  await act(async () => finish({ analysis: 'Synthetic prior-session analysis' }));
  expect(screen.queryByText('Synthetic prior-session analysis')).not.toBeInTheDocument();
  view.select();
  expect(mocks.post.mock.calls.filter(([url]) => url === '/ai/imaging')).toHaveLength(1);
});

it('clears old findings when reading the next selected image fails', async () => {
  mocks.post.mockImplementation(async url => url === '/ehr' ? [] : { analysis: 'Synthetic first image findings' });
  const view = openImaging(); view.select();
  await screen.findByText('Synthetic first image findings');
  vi.stubGlobal('FileReader', class {
    onerror: (() => void) | null = null;
    abort() {}
    readAsDataURL() { this.onerror?.(); }
  });
  view.select();
  await screen.findByRole('alert');
  expect(screen.queryByText('Synthetic first image findings')).not.toBeInTheDocument();
  expect(screen.queryByRole('button', { name: /Download AI draft/ })).not.toBeInTheDocument();
});

it.each(['timeout', '401', '429', '500', 'missing-analysis'])('does not fabricate radiology findings after %s', async failure => {
  mocks.post.mockImplementation(async (url: string) => {
    if (url === '/ehr') return [];
    if (failure === 'missing-analysis') return {};
    throw new Error(`test ${failure}`);
  });
  const view = render(<HealthRecords />);
  fireEvent.mouseDown(screen.getByRole('tab', { name: /AI/i }), { button: 0, ctrlKey: false });
  const input = view.container.querySelector('input[accept="image/*"]');
  expect(input).not.toBeNull();
  fireEvent.change(input!, { target: { files: [new File(['synthetic image'], 'test.png', { type: 'image/png' })] } });
  await waitFor(() => expect(mocks.post).toHaveBeenCalledWith('/ai/imaging', expect.any(Object)));
  // Wait beyond the original delayed fallback to exercise the actual defect.
  await new Promise(resolve => setTimeout(resolve, 1600));
  expect(screen.queryByText(/Clear lung fields|No detected fractures|DEMO MODE/)).not.toBeInTheDocument();
  expect(JSON.stringify(mocks.toast.mock.calls)).not.toMatch(/AWS Daily Limit|Simulation Mode/);
  expect(screen.getByRole('alert')).toHaveTextContent(/unavailable|could not/i);
  expect(screen.getByRole('button', { name: /Select File/i })).toBeEnabled();
});
